export interface Participant {
  ASSISTS: string;
  BOUNTY_LEVEL?: string;
  CHAMPIONS_KILLED: string;
  GOLD_EARNED: string;
  INDIVIDUAL_POSITION: string;
  MINIONS_KILLED: string;
  NAME: string;
  NEUTRAL_MINIONS_KILLED: string;
  NUM_DEATHS: string;
  SKIN: string;
  WIN: string;
}

export interface Match {
  matchId: string;
  gameDuration: number;
  gameVersion: string;
  participants: Participant[];
}

export const matches: Match[] = [
  {
    matchId: '4499231093',
    gameDuration: 1532827.0,
    gameVersion: '12.22.479.5277',
    participants: [
      {
        ASSISTS: '9',
        BOUNTY_LEVEL: '13',
        CHAMPIONS_KILLED: '18',
        GOLD_EARNED: '16813',
        INDIVIDUAL_POSITION: 'JUNGLE',
        MINIONS_KILLED: '25',
        NAME: 'm700',
        NEUTRAL_MINIONS_KILLED: '129',
        NUM_DEATHS: '4',
        SKIN: 'Ekko',
        WIN: 'Win',
      },
      {
        ASSISTS: '11',
        BOUNTY_LEVEL: '1',
        CHAMPIONS_KILLED: '5',
        GOLD_EARNED: '10008',
        INDIVIDUAL_POSITION: 'MIDDLE',
        MINIONS_KILLED: '148',
        NAME: 'nekim',
        NEUTRAL_MINIONS_KILLED: '8',
        NUM_DEATHS: '2',
        SKIN: 'Yone',
        WIN: 'Win',
      },
      {
        ASSISTS: '25',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '3',
        GOLD_EARNED: '8536',
        INDIVIDUAL_POSITION: 'UTILITY',
        MINIONS_KILLED: '8',
        NAME: 'scammo',
        NEUTRAL_MINIONS_KILLED: '0',
        NUM_DEATHS: '6',
        SKIN: 'Renata',
        WIN: 'Win',
      },
      {
        ASSISTS: '9',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '0',
        GOLD_EARNED: '8359',
        INDIVIDUAL_POSITION: 'TOP',
        MINIONS_KILLED: '156',
        NAME: 'tuxilaoban',
        NEUTRAL_MINIONS_KILLED: '0',
        NUM_DEATHS: '6',
        SKIN: 'KSante',
        WIN: 'Win',
      },
      {
        ASSISTS: '13',
        BOUNTY_LEVEL: '2',
        CHAMPIONS_KILLED: '16',
        GOLD_EARNED: '14150',
        INDIVIDUAL_POSITION: 'BOTTOM',
        MINIONS_KILLED: '171',
        NAME: 'freddiewong1',
        NEUTRAL_MINIONS_KILLED: '7',
        NUM_DEATHS: '3',
        SKIN: 'Lucian',
        WIN: 'Win',
      },
      {
        ASSISTS: '10',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '7',
        GOLD_EARNED: '11026',
        INDIVIDUAL_POSITION: 'JUNGLE',
        MINIONS_KILLED: '27',
        NAME: 'WDIJOQDWQIO9201Z',
        NEUTRAL_MINIONS_KILLED: '133',
        NUM_DEATHS: '5',
        SKIN: 'Shyvana',
        WIN: 'Fail',
      },
      {
        ASSISTS: '5',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '5',
        GOLD_EARNED: '9959',
        INDIVIDUAL_POSITION: 'TOP',
        MINIONS_KILLED: '118',
        NAME: 'Prismack',
        NEUTRAL_MINIONS_KILLED: '0',
        NUM_DEATHS: '6',
        SKIN: 'Aatrox',
        WIN: 'Fail',
      },
      {
        ASSISTS: '8',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '2',
        GOLD_EARNED: '7686',
        INDIVIDUAL_POSITION: 'BOTTOM',
        MINIONS_KILLED: '102',
        NAME: 'DjCommander15',
        NEUTRAL_MINIONS_KILLED: '0',
        NUM_DEATHS: '15',
        SKIN: 'Draven',
        WIN: 'Fail',
      },
      {
        ASSISTS: '10',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '5',
        GOLD_EARNED: '9666',
        INDIVIDUAL_POSITION: 'UTILITY',
        MINIONS_KILLED: '37',
        NAME: '248ˉ',
        NEUTRAL_MINIONS_KILLED: '0',
        NUM_DEATHS: '9',
        SKIN: 'Heimerdinger',
        WIN: 'Fail',
      },
      {
        ASSISTS: '2',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '2',
        GOLD_EARNED: '9595',
        INDIVIDUAL_POSITION: 'MIDDLE',
        MINIONS_KILLED: '167',
        NAME: 'lvory',
        NEUTRAL_MINIONS_KILLED: '12',
        NUM_DEATHS: '7',
        SKIN: 'Nocturne',
        WIN: 'Fail',
      },
    ],
  },
  {
    matchId: '4499268607',
    gameDuration: 1958024.0,
    gameVersion: '12.22.479.5277',
    participants: [
      {
        ASSISTS: '17',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '10',
        GOLD_EARNED: '14531',
        INDIVIDUAL_POSITION: 'JUNGLE',
        MINIONS_KILLED: '59',
        NAME: 'm700',
        NEUTRAL_MINIONS_KILLED: '102',
        NUM_DEATHS: '15',
        SKIN: 'Hecarim',
        WIN: 'Fail',
      },
      {
        ASSISTS: '5',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '2',
        GOLD_EARNED: '9468',
        INDIVIDUAL_POSITION: 'TOP',
        MINIONS_KILLED: '173',
        NAME: 'tuxilaoban',
        NEUTRAL_MINIONS_KILLED: '0',
        NUM_DEATHS: '13',
        SKIN: 'Aatrox',
        WIN: 'Fail',
      },
      {
        ASSISTS: '10',
        BOUNTY_LEVEL: '2',
        CHAMPIONS_KILLED: '16',
        GOLD_EARNED: '15048',
        INDIVIDUAL_POSITION: 'MIDDLE',
        MINIONS_KILLED: '127',
        NAME: 'nekim',
        NEUTRAL_MINIONS_KILLED: '3',
        NUM_DEATHS: '7',
        SKIN: 'Zac',
        WIN: 'Fail',
      },
      {
        ASSISTS: '20',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '4',
        GOLD_EARNED: '10169',
        INDIVIDUAL_POSITION: 'UTILITY',
        MINIONS_KILLED: '24',
        NAME: 'scammo',
        NEUTRAL_MINIONS_KILLED: '6',
        NUM_DEATHS: '12',
        SKIN: 'Renata',
        WIN: 'Fail',
      },
      {
        ASSISTS: '13',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '7',
        GOLD_EARNED: '13295',
        INDIVIDUAL_POSITION: 'BOTTOM',
        MINIONS_KILLED: '185',
        NAME: 'freddiewong1',
        NEUTRAL_MINIONS_KILLED: '3',
        NUM_DEATHS: '9',
        SKIN: 'Swain',
        WIN: 'Fail',
      },
      {
        ASSISTS: '27',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '0',
        GOLD_EARNED: '9653',
        INDIVIDUAL_POSITION: 'UTILITY',
        MINIONS_KILLED: '22',
        NAME: '248ˉ',
        NEUTRAL_MINIONS_KILLED: '2',
        NUM_DEATHS: '8',
        SKIN: 'Bard',
        WIN: 'Win',
      },
      {
        ASSISTS: '18',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '7',
        GOLD_EARNED: '13134',
        INDIVIDUAL_POSITION: 'JUNGLE',
        MINIONS_KILLED: '15',
        NAME: 'WDIJOQDWQIO9201Z',
        NEUTRAL_MINIONS_KILLED: '146',
        NUM_DEATHS: '7',
        SKIN: 'Ivern',
        WIN: 'Win',
      },
      {
        ASSISTS: '10',
        BOUNTY_LEVEL: '1',
        CHAMPIONS_KILLED: '17',
        GOLD_EARNED: '18059',
        INDIVIDUAL_POSITION: 'TOP',
        MINIONS_KILLED: '218',
        NAME: 'Prismack',
        NEUTRAL_MINIONS_KILLED: '20',
        NUM_DEATHS: '6',
        SKIN: 'Yone',
        WIN: 'Win',
      },
      {
        ASSISTS: '5',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '5',
        GOLD_EARNED: '11025',
        INDIVIDUAL_POSITION: 'BOTTOM',
        MINIONS_KILLED: '106',
        NAME: 'DjCommander15',
        NEUTRAL_MINIONS_KILLED: '9',
        NUM_DEATHS: '9',
        SKIN: 'Draven',
        WIN: 'Win',
      },
      {
        ASSISTS: '9',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '27',
        GOLD_EARNED: '18918',
        INDIVIDUAL_POSITION: 'MIDDLE',
        MINIONS_KILLED: '156',
        NAME: 'lvory',
        NEUTRAL_MINIONS_KILLED: '28',
        NUM_DEATHS: '9',
        SKIN: 'Qiyana',
        WIN: 'Win',
      },
    ],
  },
  {
    matchId: '4499889518',
    gameDuration: 1345906.0,
    gameVersion: '12.22.479.5277',
    participants: [
      {
        ASSISTS: '4',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '2',
        GOLD_EARNED: '7039',
        INDIVIDUAL_POSITION: 'UTILITY',
        MINIONS_KILLED: '44',
        NAME: 'freddiewong1',
        NEUTRAL_MINIONS_KILLED: '0',
        NUM_DEATHS: '7',
        SKIN: 'Lux',
        WIN: 'Fail',
      },
      {
        ASSISTS: '5',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '1',
        GOLD_EARNED: '8704',
        INDIVIDUAL_POSITION: 'JUNGLE',
        MINIONS_KILLED: '26',
        NAME: 'nekim',
        NEUTRAL_MINIONS_KILLED: '100',
        NUM_DEATHS: '6',
        SKIN: 'Rengar',
        WIN: 'Fail',
      },
      {
        ASSISTS: '1',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '5',
        GOLD_EARNED: '8446',
        INDIVIDUAL_POSITION: 'BOTTOM',
        MINIONS_KILLED: '104',
        NAME: 'DjCommander15',
        NEUTRAL_MINIONS_KILLED: '0',
        NUM_DEATHS: '11',
        SKIN: 'Draven',
        WIN: 'Fail',
      },
      {
        ASSISTS: '0',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '4',
        GOLD_EARNED: '7608',
        INDIVIDUAL_POSITION: 'MIDDLE',
        MINIONS_KILLED: '135',
        NAME: '248ˉ',
        NEUTRAL_MINIONS_KILLED: '0',
        NUM_DEATHS: '7',
        SKIN: 'Lillia',
        WIN: 'Fail',
      },
      {
        ASSISTS: '0',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '0',
        GOLD_EARNED: '7064',
        INDIVIDUAL_POSITION: 'TOP',
        MINIONS_KILLED: '134',
        NAME: 'skyl4r',
        NEUTRAL_MINIONS_KILLED: '5',
        NUM_DEATHS: '12',
        SKIN: 'Yasuo',
        WIN: 'Fail',
      },
      {
        ASSISTS: '4',
        BOUNTY_LEVEL: '4',
        CHAMPIONS_KILLED: '7',
        GOLD_EARNED: '11567',
        INDIVIDUAL_POSITION: 'MIDDLE',
        MINIONS_KILLED: '176',
        NAME: 'tuxilaoban',
        NEUTRAL_MINIONS_KILLED: '7',
        NUM_DEATHS: '3',
        SKIN: 'Sett',
        WIN: 'Win',
      },
      {
        ASSISTS: '13',
        BOUNTY_LEVEL: '3',
        CHAMPIONS_KILLED: '9',
        GOLD_EARNED: '11598',
        INDIVIDUAL_POSITION: 'BOTTOM',
        MINIONS_KILLED: '133',
        NAME: 'scammo',
        NEUTRAL_MINIONS_KILLED: '14',
        NUM_DEATHS: '5',
        SKIN: 'Caitlyn',
        WIN: 'Win',
      },
      {
        ASSISTS: '1',
        BOUNTY_LEVEL: '17',
        CHAMPIONS_KILLED: '17',
        GOLD_EARNED: '13179',
        INDIVIDUAL_POSITION: 'TOP',
        MINIONS_KILLED: '166',
        NAME: 'Prismack',
        NEUTRAL_MINIONS_KILLED: '11',
        NUM_DEATHS: '0',
        SKIN: 'Gwen',
        WIN: 'Win',
      },
      {
        ASSISTS: '16',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '4',
        GOLD_EARNED: '9553',
        INDIVIDUAL_POSITION: 'JUNGLE',
        MINIONS_KILLED: '27',
        NAME: 'm700',
        NEUTRAL_MINIONS_KILLED: '75',
        NUM_DEATHS: '1',
        SKIN: 'MonkeyKing',
        WIN: 'Win',
      },
      {
        ASSISTS: '12',
        BOUNTY_LEVEL: '3',
        CHAMPIONS_KILLED: '6',
        GOLD_EARNED: '8463',
        INDIVIDUAL_POSITION: 'UTILITY',
        MINIONS_KILLED: '17',
        NAME: 'NotSoSlimShadey',
        NEUTRAL_MINIONS_KILLED: '1',
        NUM_DEATHS: '3',
        SKIN: 'Morgana',
        WIN: 'Win',
      },
    ],
  },
  {
    matchId: '4499953086',
    gameDuration: 2175237.0,
    gameVersion: '12.22.479.5277',
    participants: [
      {
        ASSISTS: '11',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '3',
        GOLD_EARNED: '13106',
        INDIVIDUAL_POSITION: 'TOP',
        MINIONS_KILLED: '224',
        NAME: 'Prismack',
        NEUTRAL_MINIONS_KILLED: '7',
        NUM_DEATHS: '11',
        SKIN: 'Yasuo',
        WIN: 'Fail',
      },
      {
        ASSISTS: '17',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '3',
        GOLD_EARNED: '9087',
        INDIVIDUAL_POSITION: 'UTILITY',
        MINIONS_KILLED: '28',
        NAME: 'NotSoSlimShadey',
        NEUTRAL_MINIONS_KILLED: '0',
        NUM_DEATHS: '10',
        SKIN: 'Blitzcrank',
        WIN: 'Fail',
      },
      {
        ASSISTS: '16',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '18',
        GOLD_EARNED: '20790',
        INDIVIDUAL_POSITION: 'JUNGLE',
        MINIONS_KILLED: '50',
        NAME: 'm700',
        NEUTRAL_MINIONS_KILLED: '163',
        NUM_DEATHS: '8',
        SKIN: 'Kayn',
        WIN: 'Fail',
      },
      {
        ASSISTS: '9',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '9',
        GOLD_EARNED: '14533',
        INDIVIDUAL_POSITION: 'MIDDLE',
        MINIONS_KILLED: '207',
        NAME: 'tuxilaoban',
        NEUTRAL_MINIONS_KILLED: '11',
        NUM_DEATHS: '10',
        SKIN: 'Ryze',
        WIN: 'Fail',
      },
      {
        ASSISTS: '6',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '7',
        GOLD_EARNED: '14815',
        INDIVIDUAL_POSITION: 'BOTTOM',
        MINIONS_KILLED: '236',
        NAME: 'scammo',
        NEUTRAL_MINIONS_KILLED: '6',
        NUM_DEATHS: '11',
        SKIN: 'Kaisa',
        WIN: 'Fail',
      },
      {
        ASSISTS: '14',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '4',
        GOLD_EARNED: '12711',
        INDIVIDUAL_POSITION: 'JUNGLE',
        MINIONS_KILLED: '32',
        NAME: 'skyl4r',
        NEUTRAL_MINIONS_KILLED: '139',
        NUM_DEATHS: '11',
        SKIN: 'Ezreal',
        WIN: 'Win',
      },
      {
        ASSISTS: '6',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '14',
        GOLD_EARNED: '17383',
        INDIVIDUAL_POSITION: 'MIDDLE',
        MINIONS_KILLED: '222',
        NAME: 'nekim',
        NEUTRAL_MINIONS_KILLED: '10',
        NUM_DEATHS: '8',
        SKIN: 'Syndra',
        WIN: 'Win',
      },
      {
        ASSISTS: '12',
        BOUNTY_LEVEL: '8',
        CHAMPIONS_KILLED: '12',
        GOLD_EARNED: '18944',
        INDIVIDUAL_POSITION: 'TOP',
        MINIONS_KILLED: '268',
        NAME: '248ˉ',
        NEUTRAL_MINIONS_KILLED: '16',
        NUM_DEATHS: '5',
        SKIN: 'Fiora',
        WIN: 'Win',
      },
      {
        ASSISTS: '18',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '8',
        GOLD_EARNED: '11386',
        INDIVIDUAL_POSITION: 'UTILITY',
        MINIONS_KILLED: '39',
        NAME: 'freddiewong1',
        NEUTRAL_MINIONS_KILLED: '4',
        NUM_DEATHS: '7',
        SKIN: 'Zac',
        WIN: 'Win',
      },
      {
        ASSISTS: '8',
        BOUNTY_LEVEL: '0',
        CHAMPIONS_KILLED: '11',
        GOLD_EARNED: '14997',
        INDIVIDUAL_POSITION: 'BOTTOM',
        MINIONS_KILLED: '148',
        NAME: 'DjCommander15',
        NEUTRAL_MINIONS_KILLED: '12',
        NUM_DEATHS: '9',
        SKIN: 'Tristana',
        WIN: 'Win',
      },
    ],
  },
];
